name: Torrent2Drive

run-name: "Torrent2Drive for ${{ inputs.CustomDest || inputs.JobDestType }}"

on:
  workflow_dispatch:
    inputs:
      TorrentURL:
        description: "TorrentURL, https://site.address/file.torrent"
        required: false
        type: string
      MagnetURI:
        description: "MagnetURI, magnet:?xt=urn:btih:HASH&dn=NAME&tr=TRACKER"
        required: false
        type: string
      FileIdx:
        description: "FileIdx, Range of Files in Torrent"
        required: false
        type: string
      JobDestType:
        description: "Destination, AniMaze / Public / ShareZone"
        required: false
        type: choice
        options:
        - "AniMaze"
        - "Public"
        - "ShareZone"
        - ""
      CustomDest:
        description: "Custom Destination Folder"
        required: false
        type: string
        default: ""
      CustomEnvs:
        description: "Custom Env Vars (pipe-separated), Seed|SeedTime|.."
        type: string
        required: false

env:
  baseScrAddr: "https://gist.github.com/rokibhasansagar/defcf75ce810fa40ac6200d089de969b"
  TorrentURL: ${{ github.event.inputs.TorrentURL }}
  MagnetURI: ${{ github.event.inputs.MagnetURI }}
  FileIdx: ${{ github.event.inputs.FileIdx }}
  UploadPath: ${{ github.event.inputs.JobDestType || github.event.inputs.CustomDest }}
  CustomEnvs: ${{ github.event.inputs.CustomEnvs }}
  TorrDLoader_Hash: ${{ secrets.TorrDLoader_Hash }}
  RCLONE_CONFIG_HASH: ${{ secrets.RCLONE_CONFIG_HASH }}

jobs:
  transloader:
    name: "Torrent Downloader"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'main'
      - name: GitHub Auth
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Run TorrDLoader Script
        run: |
          # Prepare Custom Env Var Overrides
          if [[ -n "$CustomEnvs" ]]; then
            while IFS='=' read -r k v; do
              [[ -z "$k" ]] && continue
              export "$k"="${v//\"/}"
              echo "$k"="${v//\"/}"
            done < <(sed 's/|/\n/g' <<<"$CustomEnvs")
          fi
          unset k v 2>/dev/null || true
          # Execute Script Stealthly
          eval 'set -eo pipefail' 2>/dev/null
          eval 'set +o history' 2>/dev/null

          export baseScrHash="$(git ls-remote -q "${baseScrAddr}" HEAD | awk '{print $1}')"
          echo -e "latestRevision=${baseScrHash}"

          # Get Scriptlets
          ( curl -sL "${baseScrAddr}/raw/${baseScrHash}/zzSystemdResolved.fix" | bash 2>/dev/null || true )
          curl -sL "${baseScrAddr}/raw/${baseScrHash}/torrent2drive.base.sh" -o torrent2drive.base.script
          for split in zUploadGeneral z{Mod,Upload}AniMaze zSeed; do
            curl -sL "${baseScrAddr}/raw/${baseScrHash}/${split}.block" -O
          done
          sed -i '1,2d' *.block

          # Put Together The Complete Script
          if [[ "${UploadPath}" == "AniMaze" ]]; then
            sed -i -e '/__Modification Block__/r zModAniMaze.block' ./torrent2drive.base.script
            sed -i -e '/__Upload Block__/r zUploadAniMaze.block' ./torrent2drive.base.script
          else
            sed -i -e '/__Upload Block__/r zUploadGeneral.block' ./torrent2drive.base.script
          fi

          sed -e '/__Seed Block__/r zSeed.block' ./torrent2drive.base.script >./torrentLoader.sh

          # Run Script
          source ./torrentLoader.sh
          eval 'set -o history' 2>/dev/null

